name = "Sentencize"
uuid = "7dcf698f-69e3-471c-af7e-711815da818c"
authors = ["Astariul <remondnicola@gmail.com> and all contributors"]
version = "0.1.0"

[compat]
Aqua = "0.7"
Test = "<0.0.1, 1"
julia = "1.6"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
